query {
  pairings {
    edges {
      node {
        pairings_gql {
          images {
            image {
              sourceUrl
            }
          }
        }
        slug
        title
      }
    }
  }
}
