

fragment textAndImageContent on Vino_page_Fc_HomeFc_TextAndImageContent {
  content
  fieldGroupName
  buttons {
    label
    url
    fieldGroupName
  }
  orientation
  subTitle
  title
  images {
    image {
      sourceUrl
    }
  }
}


fragment showcase on Vino_page_Fc_HomeFc_Showcase {
  content
  fieldGroupName
  subTitle
  title
  items {
    content
    link
    title
    image {
      sourceUrl
    }
  }
}

fragment centerText on Vino_page_Fc_HomeFc_CenterText {
  content
  fieldGroupName
  title
  subTitle
  buttons {
    buttonUrl
    label
  }
  imageButtons {
    image {
      sourceUrl
    }
    routePath
    subTitle
    title
    content
  }
}

fragment heroImage on Vino_page_Fc_HomeFc_HeroImage {
  image {
    sourceUrl
  }
}

fragment spacer on Vino_page_Fc_HomeFc_Spacer {
  fieldGroupName
}

fragment textArea on Vino_page_Fc_HomeFc_TextArea {
  content
  fieldGroupName
}

fragment imageContent on Vino_page_Fc_HomeFc_Image {
  fieldGroupName
  image {
    sourceUrl
  }
}

fragment contactUs on Vino_page_Fc_HomeFc_ContactUs {
  address
  email
  phoneNumber
}

query GET_CUSTOM_POST($slug: String!) {
  vino_pageBy(slug: $slug) {
      slug
      metas {
        metatags {
          content
          hid
          name
        }
      }
      og_tags {
        ogTags {
          content
          hid
          property
        }
      }
      fc {
        homeFc {
          ...contactUs
          ...textAndImageContent
          ...centerText
          ...heroImage
          ...showcase
          ...spacer
          ...textArea
          ...imageContent
        }
      }
  }
}