query GET_CUSTOM_POST($slug: String!) {
  pairingBy(slug: $slug) {
    title
    chef {
      bio
      name
      photo {
        sourceUrl
      }
    }
    pairings_gql {
      heroImage {
        sourceUrl
      }
      content
      backgroundColor
      images {
        image {
          sourceUrl
        }
      }
      items {
        content
        images {
          image {
            sourceUrl
          }
          label
        }
        title
      }
      subTitle
    }
  }
}