query {
   shop_items {
    edges {
      node {
        shop_gql {
          buyNowUrl
          details
          fieldGroupName
          description
          images {
            image {
              sourceUrl
            }
          }
          price
          thumbnail {
            sourceUrl
          }
          subTitle
        }
        title
        slug
      }
    }
  }
}