query GET_CUSTOM_POST($slug: String!) {
  shop_itemBy(slug: $slug) {
    title
    slug
    shop_gql {
      buyNowUrl
      details
      description
      images {
        image {
          sourceUrl
        }
      }
      price
      subTitle
    }
  }
}